[project]
name = "esp32-setup"
version = "0.1.0"
description = "ESP32 Development Setup"
requires-python = ">=3.11,<3.12"
dependencies = [
    "esptool>=5.0.2",
    "micropy-cli>=4.2.2",
    "micropython-esp32-stubs>=1.26.0.post1",
    "setuptools==80.0.0",
]
